<?php

/**
 * @file
 * Primary module hooks for Tour Enhancements module.
 */

use Drupal\tour\Entity\Tour;

/**
 * Implements hook_page_bottom().
 *
 * Adds a route parameter for bundle type to nodes and node forms.
 */
function tour_enhancements_page_bottom(array &$page_bottom) {
  // First thing, check permissions.
  if (!\Drupal::currentUser()->hasPermission('access tour')) {
    return;
  }
  // Load all of the items and match on route name.
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  $results = \Drupal::entityQuery('tour')
    ->condition('routes.*.route_name', $route_name)
    ->execute();
  if (!empty($results) && $tours = Tour::loadMultiple(array_keys($results))) {
    foreach ($tours as $id => $tour) {
      // Get the parameters.
      $params = $route_match->getRawParameters()->all();
      // Include 'bundle' as parameter to use as match.
      // You could also add additional if (ie if a node had a specific field).
      if ($bundle = $route_match->getParameter('node')) {
        $params['bundle'] = $route_match->getParameter('node')->bundle();
      }
      // Match on the parameters.
      if (!$tour->hasMatchingRoute($route_name, $params)) {
        unset($tours[$id]);
      }
    }
    if (!empty($tours)) {
      $page_bottom['tour'] = \Drupal::entityTypeManager()
        ->getViewBuilder('tour')
        ->viewMultiple($tours, 'full');
    }
  }
}
